* Reviewer 1

This is an intersting reproducible paper. Since paper is neuro oriented, 
I include some comments from a statistical point of view.

Introduction:

  * eq. 2: correct equation is \sqrt{K_{12}/\pi}
  * Fig. 3: I wonder why there is no confidence interval. It will gives
    an estimate of d_\mbox{min}.
  * Choice of d_\mbox{min} is questionnable. You mainly described an
    hard-core process (or Strauss process). You may find the set of d,
    the exclusion distance compatible with your data. Compatible means
    that the process does not go out the confidence interval (at 5%
    level for example).

Bivariate pattern:

Fig 4 since we mostly print inblack and white, I personnaly prefer 
different symbols than different colors.

  * Why do you present the results for functional independence ?
  * According to Fig. 6 you reject random for distances between 100 and
    150. Please discuss.
  * In order to avoid confusion among readers, please precise difference
    between independence and random labelling.
  * Fig. 7: By simulating CSR, you may construct confidence interval.

Future directions:

You may be interested to read paper like

Illian, J., Benson, E., Crawford, J., & Staines, H. (2006). Principal 
component analysis for spatial point processes—assessing the 
appropriateness of the approach in an ecological context. In Case 
studies in spatial point process modeling (pp. 135-150). Springer New York.

Reproductible research:
Just perfect !! Thanks :-)

* Reviewer 2

Overall I found the manuscript an interesting read and the author has 
made an impressive effort at maximal reproducibility. The code runs as 
advertised.

I just have the following (minor) remarks:

  * The introduction needs more background. As it is the text jumps from
    the fact that the retina does unique computations to (x,y,z)
    positions, and doesn’t explain why we should care about the latter.
  * The title is a bit too general considering the paper’s contents. I’d
    replace “in the visual system” with “in the retina”, since no other
    structure is mentioned.
  * Confidence bands are missing from fig 3 and fig 7B.
  * I know very little about how the retina develops, but maybe the
    author could explain why complete spatial randomness would be a
    reasonable null model? Somas are to a good approximation 2D objects,
    but whole neurons aren’t. Dendrites and axons need to be packed in
    there as well, doesn’t that constrain where somas can be?
  * I’m not sure to what extent this belongs in a review paper, but
    second-order statistics such as Ripley’s K function become much
    harder to use when you can’t assume a uniform intensity function.
    Does uniform density really holds in the retinal mosaics the author
    examines?

I appreciated that the author put an entire R package on github for easy 
distribution, and docker sounds extremely useful. My only worry is that 
we rely on private companies (github, docker) that might stop providing 
free services any time. Perhaps reproducibility would require public, 
durable infrastructure but that’s not a problem for this review to solve.

